### ISSUE TITLE
Documentation - Sending a message from Python to Erlang seems wrong

### ISSUE THREAD

**Issue by lawik** [hdima/erlport#34]
I am guessing that this is erlang code. It does not look like python code :)

http://erlport.org/docs/python.html#send-messages-from-python-to-erlang

I was looking for this particular stuff so now I'm a bit stumped on where to start.

**Comment by beano** [comment]
I don't think the docs are wrong. It's sending a message  to erlang from python from erlang :). I suspect it is documented like this because you need an erlang pid to address and the example just makes this explicit.

Python code might  look something like this (not tested)

import erlport.erlang
erlport.erlang.cast(erlang_pid, "hello world")

Your job is to work out how to set the erlang_pid variable. 

HTH 
- Beano

**Comment by lawik** [comment]
I see. Appreciate the clarification. It was quite confusing :)
